# Generated by Django 6.0 on 2025-12-14 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyusage",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.store"
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.store"
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.item"
            ),
        ),
        migrations.AddField(
            model_name="dailyusage",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.item"
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="users.store",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="default_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.location",
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.location"
            ),
        ),
        migrations.AddField(
            model_name="productionlog",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.store"
            ),
        ),
        migrations.AddField(
            model_name="productionlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to="inventory.item",
            ),
        ),
        migrations.AddField(
            model_name="productionlog",
            name="recipe",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.recipe",
            ),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="ingredient_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="used_in_recipes",
                to="inventory.item",
            ),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients",
                to="inventory.recipe",
            ),
        ),
        migrations.AddField(
            model_name="unitconversion",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversions",
                to="inventory.item",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="yield_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.unitconversion",
            ),
        ),
        migrations.AddField(
            model_name="variancelog",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.item"
            ),
        ),
        migrations.AddField(
            model_name="variancelog",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.location"
            ),
        ),
        migrations.AddField(
            model_name="variancelog",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.store"
            ),
        ),
        migrations.AddField(
            model_name="variancelog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyusage",
            unique_together={("store", "item", "date")},
        ),
    ]
