# Generated by Django 6.0 on 2025-12-16 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="default_location",
        ),
        migrations.AlterField(
            model_name="item",
            name="shelf_life_hours",
            field=models.IntegerField(blank=True, default=24, null=True),
        ),
        migrations.CreateModel(
            name="StoreItemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("par", models.FloatField(default=0.0)),
                (
                    "default_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.location",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_settings",
                        to="inventory.item",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_settings",
                        to="users.store",
                    ),
                ),
            ],
            options={
                "unique_together": {("store", "item")},
            },
        ),
    ]
