# Generated by Django 6.0 on 2025-12-16 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_item_default_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionlog',
            name='target_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location'),
        ),
    ]
