# Generated by Django 6.0 on 2025-12-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_productionlog_target_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='shelf_life_hours',
        ),
        migrations.AddField(
            model_name='item',
            name='shelf_life_days',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
