# Generated by Django 6.0 on 2025-12-16 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_item_shelf_life_hours_item_shelf_life_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient_item',
            field=models.ForeignKey(limit_choices_to={'type': 'ingredient'}, on_delete=django.db.models.deletion.CASCADE, related_name='used_in_recipes', to='inventory.item'),
        ),
    ]
