# Generated by Django 6.0 on 2025-12-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_instructions_recipe_description_recipe_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='description',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_steps/'),
        ),
    ]
