# Generated by Django 6.0 on 2025-12-16 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_recipe_description_remove_recipe_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeStepIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(help_text="e.g., '2 cups', '100g'", max_length=50)),
                ('ingredient', models.ForeignKey(limit_choices_to={'type': 'ingredient'}, on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='inventory.recipestep')),
            ],
        ),
    ]
