# Generated by Django 6.0 on 2025-12-16 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_recipestepingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipestepingredient',
            name='quantity',
        ),
    ]
