# Generated by Django 6.0 on 2025-12-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_item_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktakesession',
            name='type',
            field=models.CharField(choices=[('FULL', 'Full Stocktake'), ('ADDITION', 'Addition / Delivery')], default='FULL', max_length=20),
        ),
    ]
